# -*- coding: utf-8 -*-
"""TD_IA_RL-RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elWxs1FjM77T8PRxfkDQEjum2EPPr3aB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Tâche 1 :
###### Exploitez la base de données "possum.csv". Préparez cette base de données de manière à ce qu’elle soit correctement nettoyée.
###### Puis affichez les données des descripteurs ciblés
"""

# Charger la base de données
df = pd.read_csv('possum.csv')

# Afficher les premières lignes du DataFrame pour vérifier son contenu
print(df.head())

# Vérification des informations sur les colonnes
print(df.info())

# Affichage des descripteurs ciblés : footlength et earconch
df_descriptors = df[['footlgth', 'earconch']]
print(df_descriptors.head())

# Vérification des valeurs manquantes
print(df_descriptors.isnull().sum())

# Suppression des lignes avec des valeurs manquantes
df_clean = df_descriptors.dropna()

# Vérification
print(df_clean.isnull().sum())

print(df_clean.head())
print(df_clean.dtypes)

# Visualisation de la relation entre footlength et earconch avec un scatter plot
footlgth = df_clean['footlgth']
earconch = df_clean['earconch']
plt.scatter(footlgth, earconch)
plt.title('Relation entre footlgth et earconch')
plt.xlabel('Longueur d''empreinte')
plt.ylabel('Taille pavillon de l''oreille')
plt.show()

def predict_model(alpha, beta, X):
    return alpha * X + beta

def mean_square_error(y_reel, y_pred):
    mse = ((y_reel - y_pred) ** 2).mean()
    return mse

# Exemples de paramètres
alphas_betas = [(0.25, 0.5), (0.75, 1), (1, 2)]

# Calcul des MSE pour chaque modèle
for alpha, beta in alphas_betas:
    predictions = predict_model(alpha, beta, footlgth)
    error = mean_square_error(earconch, predictions)
    print(f"Model (alpha={alpha}, beta={beta}): MSE = {error:.3f}")

# Exemples de paramètres
alphas_betas = [(0.25, 0.5), (0.75, 1), (1, 2)]

# Créer le plot
plt.figure()
plt.scatter(footlgth, earconch, label='Données observées')  # Points observés

# Initialisation d'une liste pour stocker les MSE
mse_values = []

# Tracer chaque modèle et calculer les MSE
for alpha, beta in alphas_betas:
    predictions = predict_model(alpha, beta, footlgth)
    error = mean_square_error(earconch, predictions)
    mse_values.append((alpha, beta, error))  # Stocker les résultats
    plt.plot(footlgth, predictions, label=f'Modèle (alpha={alpha}, beta={beta})')

# Ajouter des annotations
plt.xlabel('Longueur d\'empreinte (footlgth)')
plt.ylabel('Taille du pavillon de l\'oreille (earconch)')
plt.title('Comparaison des modèles de régression linéaire')
plt.legend()
plt.show()

# Afficher les MSE pour chaque modèle
print("MSE pour chaque modèle :")
for alpha, beta, error in mse_values:
    print(f"Model (alpha={alpha}, beta={beta}): MSE = {error:.3f}")

# Solution 2
# Calcul des paramètres optimaux alpha et beta
def optimal_coefficients(x, y):
    x_bar = x.mean()
    y_bar = y.mean()

    # Calcul de alpha
    numerateur = ((x - x_bar) * (y - y_bar)).sum()
    denominateur = ((x - x_bar) ** 2).sum()
    alpha = numerateur / denominateur

    # Calcul de beta
    beta = y_bar - alpha * x_bar

    return alpha, beta

# Calcul des coefficients optimaux
alpha_opt, beta_opt = optimal_coefficients(footlgth, earconch)
print(f"Coefficients optimaux : alpha = {alpha_opt:.3f}, beta = {beta_opt:.3f}")

# Prédiction avec les paramètres optimaux
optimal_predictions = predict_model(alpha_opt, beta_opt, footlgth)

# Calcul de la MSE pour les paramètres optimaux
optimal_mse = mean_square_error(earconch, optimal_predictions)
print(f"Erreur quadratique moyenne (MSE) avec les paramètres optimaux : {optimal_mse:.3f}")

# Visualisation du modèle optimal
plt.figure(figsize=(10, 6))
plt.scatter(footlgth, earconch, color='blue', label='Données observées')  # Points observés
plt.plot(footlgth, optimal_predictions, color='green', label=f'Modèle optimal (MSE={optimal_mse:.3f})')
plt.xlabel('Longueur d\'empreinte (footlgth)')
plt.ylabel('Taille du pavillon de l\'oreille (earconch)')
plt.title('Modèle de régression linéaire optimal')
plt.legend()
plt.show()

# Calcul des coefficients alpha et beta

x = footlgth
y = earconch
x_bar = x.mean()
y_bar = y.mean()

# Calcul de alpha
numerator = ((x - x_bar) * (y - y_bar)).sum()
denominator = ((x - x_bar) ** 2).sum()
alpha_optimal = numerator / denominator

# Calcul de beta
beta_optimal = y_bar - alpha_optimal * x_bar

# Affichage des coefficients
print(f"Coefficients optimaux : alpha = {alpha_optimal:.3f}, beta = {beta_optimal:.3f}")

# Prédiction avec les paramètres optimaux
optimal_y_predictions = predict_model(alpha_optimal, beta_optimal, x)

# Calcul de la MSE pour les paramètres optimaux
optimal_mse = mean_square_error(y, optimal_y_predictions)
print(f"Erreur quadratique moyenne (MSE) avec les paramètres optimaux : {optimal_mse:.3f}")

# Visualisation du modèle optimal
plt.figure()
plt.scatter(x, y)  # Points observés
plt.plot(x, optimal_y_predictions, color='orange', label=f'Modèle optimal (MSE={optimal_mse:.3f})')
plt.xlabel('Longueur d\'empreinte (footlgth)')
plt.ylabel('Taille du pavillon de l\'oreille (earconch)')
plt.title('Modèle de régression linéaire optimal')
plt.legend()
plt.show()

